rewrite ^/.well-known/caldav /dav.php redirect;
rewrite ^/.well-known/carddav /dav.php redirect;

location ~ ^(.+.php)(.*)$ {
    try_files                       $fastcgi_script_name =404;
    include                         fastcgi_params;
    fastcgi_split_path_info         ^(.+.php)(.*)$;
    fastcgi_pass                    php-fpm;
    fastcgi_index                   index.php;
    fastcgi_param                   SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
